maxlength: 20
allowcolor: true
#Message which displays the player who signed the item (set to 'null' if you want to disable)
signmessage: "ยง7Item signed by {player}"
#Default color for the signature
signcolor: "ยง7"